#!/bin/bash 
# Setting aliases on environament
alias cleandocker="docker ps --filter status=dead --filter status=exited -aq | xargs -r docker rm -v; docker ps --filter status=dead --filter status=exited -aq | xargs -r docker rm -v; docker volume ls -qf dangling=true | xargs -r docker volume rm"

#checking presence
$(grep -r "docker-tools-alias-v1" ~/.bashrc) 2> /dev/null;
if [ $? -eq 1 ]; then
	echo '#docker-tools-alias-v1' >> ~/.bashrc;
	echo 'alias cleandocker="docker ps --filter status=dead --filter status=exited -aq | xargs -r docker rm -v; docker ps --filter status=dead --filter status=exited -aq | xargs -r docker rm -v; docker volume ls -qf dangling=true | xargs -r docker volume rm"' >> ~/.bashrc;
fi
